name: SAST scanning via KICS

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "30 23 * * 5" # Runs at 11:30 PM on Friday nights

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write
  security-events: write

jobs:
  KICSScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: Checkmarx/kics-github-action@05aa5eb70eede1355220f4ca5238d96b397e30a6 # v2.1.20
        with:
          path: "terraform"
          output_path: results-dir
          output_formats: "json,sarif,html"
          ignore_on_exit: results
          platform_type: terraform
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@7434149006143a4d75b82a2f411ef15b03ccc2d7 # v4.32.6
        with:
          sarif_file: ./results-dir/results.sarif
      - name: Comment on PR
        if: ${{ github.event.pull_request }}
        run: |
          sudo apt install pandoc
          pandoc -f html -t gfm ./results-dir/results.html -o ./results-dir/results.md

      - name: Comment on PR
        if: ${{ github.event.pull_request }}
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3
        with:
          file-path: ./results-dir/results.md
