name: SAST scanning via KICS

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * 5" # Runs at 11:30 PM on Friday nights

jobs:
  KICSScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: Checkmarx/kics-github-action@5373b38b35d09a400790b9e560189064d185391f # v2.1.7
        with:
          path: "terraform"
          output_path: results-dir
          output_formats: "json,sarif"
          ignore_on_exit: results
          platform-type: terraform
      - name: Show results
        run: |
          cat results-dir/results.json
          cat results-dir/results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@60168efe1c415ce0f5521ea06d5c2062adbeed1b # v3
        with:
          sarif_file: results-dir/results.sarif
