name: SAST scanning via KICS

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "30 23 * * 5" # Runs at 11:30 PM on Friday nights

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write

jobs:
  KICSScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: Checkmarx/kics-github-action@5373b38b35d09a400790b9e560189064d185391f # v2.1.7
        with:
          path: "terraform"
          output_path: results-dir
          output_formats: "json,sarif,html"
          ignore_on_exit: results
          platform-type: terraform
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@60168efe1c415ce0f5521ea06d5c2062adbeed1b # v3
        with:
          sarif_file: ./results-dir/results.sarif
      - name: Comment on PR
        if: ${{ github.event.pull_request }}
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3
        with:
          file-path: ./results-dir/results.html
