name: Reusable workflow to run aws-nuke

on:
  workflow_call:
    inputs:
      working-dir:
        required: false
        type: string
        default: "./"
      region:
        required: false
        type: string
        default: "us-east-1"
    secrets:
      OPS_ROLE_ARN:
        required: true
      ACCOUNT_ID:
        required: true
      BLOCKED_ACCOUNT_ID:
        required: true
      ACCOUNT_ROLE_ARN:
        required: true
      DISCORD_WEBHOOK_ID:
        required: true
      DISCORD_WEBHOOK_TOKEN:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true
    outputs:
      nukelog:
        description: "Log of the items nuked."
        value: ${{ jobs.NukeAccount.outputs.nukelog }}

jobs:
  NukeAccount:
    runs-on: ubuntu-latest
    outputs:
      nukelog: ${{ steps.run-nuke.outputs.nukelog }}

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.OPS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.region }}
      - name: Generate config
        working-directory: ${{ inputs.working-dir }}
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          BLOCKED_ACCOUNT_ID: ${{ secrets.BLOCKED_ACCOUNT_ID }}
        run: |
          cat ./config-template.txt | envsubst > nuke-config.yml

      - name: Setup aws-nuke
        working-directory: ${{ inputs.working-dir }}
        run: |
          chmod 0700 ./
          wget https://github.com/ekristen/aws-nuke/releases/download/v3.51.1/aws-nuke-v3.51.1-linux-amd64.tar.gz
          if [ -f ./temp ]; then echo "cleaning temp dir" && rm -f ./temp ; fi
          mkdir temp
          cd ./temp && tar zxvf ../aws-nuke-v3.51.1-linux-amd64.tar.gz
          cd ../

      - name: Run aws-nuke
        id: run-nuke
        working-directory: ${{ inputs.working-dir }}
        env:
          ASSUME_ARN: ${{ secrets.ACCOUNT_ROLE_ARN }}
        run: |
          OUT=$(aws sts assume-role --role-arn ${ASSUME_ARN} --role-session-name gha-assumed)
          export AWS_ACCESS_KEY_ID=$(echo $OUT | jq -r '.Credentials''.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $OUT | jq -r '.Credentials''.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $OUT | jq -r '.Credentials''.SessionToken')
          ./temp/aws-nuke run -c nuke-config.yml --no-dry-run --no-prompt > nukeout.log

        #  echo "nukelog<<EOF" >> $GITHUB_OUTPUT
        #  echo `cat nukeout.log` >> $GITHUB_OUTPUT
        #  echo "EOF" >> $GITHUB_OUTPUT
        #./temp/aws-nuke explain-account -c nuke-config.yml
        #aws sts get-caller-identity
      - name: Report
        working-directory: ${{ inputs.working-dir }}
        run: |
          ls -laF .
          cat nukeout.log
        # uses: tsickert/discord-webhook@v7.0.0
        # with:
        #   webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        #   username: Bill
        #   avatar-url: https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256
        #   embed-title: "Foo"
        #   embed-url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        #   embed-description: "Bar [test](https://google.com)"
        #   embed-author-name: "Bill"
        #   embed-author-icon-url: "https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256"
        #   embed-author-url: "https://google.com"
        #   embed-thumbnail-url: "https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256"
        #   embed-image-url: "https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256"
        #   embed-footer-icon-url: "https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256"
        #   embed-footer-text: "Foot text [test](https://google.com)"
        #   embed-color: 15430476
        #   embed-timestamp: "2021-09-24T02:17:53+0000"
        # uses: appleboy/discord-action@master
        # with:
        #   webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        #   webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        #   color: "#eb4034"
        #   username: "GitHub Build Bot"
        #   message: "Build log for ${{ github.repository }} on commit ${{ github.sha }}... ${{ needs.CleanSouthern.outputs.nukelog }}"
        #   file: "./nukeout.log"
