name: Periodically run aws-nuke on select AWS accounts in the ORG.

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * 6" # Runs at 11:30 PM on Saturday nights

env:
  AWS_REGION: "us-east-1"

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  CleanBobson:
    uses: ./.github/workflows/nuke-workflow.yml
    with:
      working-dir: "./aws-nuke"
    secrets:
      OPS_ROLE_ARN: ${{ secrets.GHA_NUKE_ARN }}
      ACCOUNT_ID: ${{ secrets.BOBSON_ACCOUNT_ID }}
      BLOCKED_ACCOUNT_ID: ${{ secrets.BLOCKLIST_ACCOUNT }}
      ACCOUNT_ROLE_ARN: ${{ secrets.BOBSON_ARN }}

  CleanSouthern:
    uses: ./.github/workflows/nuke-workflow.yml
    with:
      working-dir: "./aws-nuke"
    secrets:
      OPS_ROLE_ARN: ${{ secrets.GHA_NUKE_ARN }}
      ACCOUNT_ID: ${{ secrets.SOUTHERNBOY_ACCOUNT_ID }}
      BLOCKED_ACCOUNT_ID: ${{ secrets.BLOCKLIST_ACCOUNT }}
      ACCOUNT_ROLE_ARN: ${{ secrets.SOUTHERNBOY_ROLE_ARN }}
  ReportSouthern:
    runs-on: ubuntu-latest
    needs: CleanSouthern
    steps:
      - uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#eb4034"
          username: "GitHub Build Bot"
          message: "Build log for ${{ github.repository }} on commit ${{ github.sha }}... ${{ needs.CleanSouthern.outputs.nukelog }}"

  CleanNinja:
    uses: ./.github/workflows/nuke-workflow.yml
    with:
      working-dir: "./aws-nuke"
    secrets:
      OPS_ROLE_ARN: ${{ secrets.GHA_NUKE_ARN }}
      ACCOUNT_ID: ${{ secrets.NINJA_ACCOUNT_ID }}
      BLOCKED_ACCOUNT_ID: ${{ secrets.BLOCKLIST_ACCOUNT }}
      ACCOUNT_ROLE_ARN: ${{ secrets.NINJA_ROLE_ARN }}
