# This is a basic workflow to help you get started with Actions
name: Periodically run aws-nuke on select AWS accounts in the ORG.

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * 6" # Runs at 11:30 PM on Saturday nights

env:
  AWS_REGION: "us-east-1" #Change to reflect your Region

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  CleanBobson:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.GHA_NUKE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Generate config
        env:
          ACCOUNT_ID: ${{ secrets.BOBSON_ACCOUNT_ID }}
          BLOCKED_ACCOUNT_ID: ${{ secrets.BLOCKLIST_ACCOUNT }}
        run: |
          cat ./aws-nuke/config-template.txt | envsubst | tee nuke-config.yml
      - name: Setup aws-nuke
        run: |
          chmod 0700 ./
          wget https://github.com/ekristen/aws-nuke/releases/download/v3.51.1/aws-nuke-v3.51.1-linux-amd64.tar.gz
          if [ -f ./aws-nuke ]; then rm -f ./aws-nuke ; fi
          tar zxvf aws-nuke-v3.51.1-linux-amd64.tar.gz
      - name: Dry-Run aws-nuke
        env:
          ASSUME_ARN: ${{ secrets.BOBSON_ARN }}
        run: |
          OUT=$(aws sts assume-role --role-arn ${ASSUME_ARN} --role-session-name gha-assumed)
          export AWS_ACCESS_KEY_ID=$(echo $OUT | jq -r '.Credentials''.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $OUT | jq -r '.Credentials''.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $OUT | jq -r '.Credentials''.SessionToken')
          #aws sts get-caller-identity
          ./aws-nuke explain-account -c nuke-config.yml
